In [1]:
import pandas as pd
df=pd.read_csv("c:/Users/EMA 4 - 208/Documents/CDP/df_sucio BUENO.csv")
df

,Unnamed: 0,season,round,circuit_id,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,driver,...,grid,podium,driver_points,driver_wins,driver_standings_pos,constructor_points,constructor_wins,constructor_standings_pos,qualifying_time,driver_age
0,14.0,1983.0,1.0,Auto%#,False,0.0,True,0.0,False,keke_rosberg,...,1,15,0.0,0.0,0.0,0.0,0.0,0,0.0,34.0
1,5.0,1983.0,1.0,jacarepagua,False,0.0,True,0.0,False,prost,...,2,6,0.0,0.0,0.0,0.0,0.0,0,0.2,28.0
2,3.0,1983.0,NaN,jacarepagua,False,0.0,True,0.0,False,tambay,...,3,4,0.0,0.0,0.0,0.0,0.0,0,0.3,33.0
3,0.0,1983.0,1.0,jacarepagua,False,0.0,True,0.0,NaN,piquet,...,4,1,0.0,0.0,0.0,0.0,0.0,0,0.6,30.0
4,6.0,1983.0,1.0,jacarepagua,False,0.0,True,0.0,False,warwick,...,5,7,0.0,0.0,0.0,0.0,0.0,0,0.7,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16636,4064.0,1993.0,1.0,kyalami,True,0.0,False,0.0,False,blundell,...,8,NaN,0.0,0.0,0.0,0.0,0.0,NaN,3.0,26.0
16637,5893.0,1997.0,13.0,monza,False,0.0,True,0.0,False,irvine,...,10,8,18.0,0.0,6.0,84.0,4.0,1,0.9,31.0
16638,9746.0,2008.0,7.0,villeneuve,True,0.0,False,0.0,False,fisichella,...,17,14,0.0,0.0,18.0,0.0,0.0,10,1.3,35.0
16639,434.0,1984.0,3.0,zolder,False,0.0,False,0.0,False,arnoux,...,2,3,0.0,0.0,23.0,0.0,0.0,11,0.6,35.0
16640,8554.0,2005.0,5.0,catalunya,True,0.0,False,0.0,False,coulthard,...,9,8,9.0,0.0,7.0,NaN,0.0,6,2.8,34.0

In [2]:
df.info

<bound method DataFrame.info of        Unnamed: 0  season  round   circuit_id weather_warm  weather_cold  \
0            14.0  1983.0    1.0       Auto%#        False           0.0
1             5.0  1983.0    1.0  jacarepagua        False           0.0
2             3.0  1983.0    NaN  jacarepagua        False           0.0
3             0.0  1983.0    1.0  jacarepagua        False           0.0
4             6.0  1983.0    1.0  jacarepagua        False           0.0
...           ...     ...    ...          ...          ...           ...
16636      4064.0  1993.0    1.0      kyalami         True           0.0
16637      5893.0  1997.0   13.0        monza        False           0.0
16638      9746.0  2008.0    7.0   villeneuve         True           0.0
16639       434.0  1984.0    3.0       zolder        False           0.0
16640      8554.0  2005.0    5.0    catalunya         True           0.0

      weather_dry  weather_wet weather_cloudy        driver  ... grid podium  \
0            True          0.0          False  keke_rosberg  ...    1     15
1            True          0.0          False         prost  ...    2      6
2            True          0.0          False        tambay  ...    3      4
3            True          0.0            NaN        piquet  ...    4      1
4            True          0.0          False       warwick  ...    5      7
...           ...          ...            ...           ...  ...  ...    ...
16636       False          0.0          False      blundell  ...    8    NaN
16637        True          0.0          False        irvine  ...   10      8
16638       False          0.0          False    fisichella  ...   17     14
16639       False          0.0          False        arnoux  ...    2      3
16640       False          0.0          False     coulthard  ...    9      8

      driver_points driver_wins  driver_standings_pos  constructor_points  \
0               0.0         0.0                   0.0                 0.0
1               0.0         0.0                   0.0                 0.0
2               0.0         0.0                   0.0                 0.0
3               0.0         0.0                   0.0                 0.0
4               0.0         0.0                   0.0                 0.0
...             ...         ...                   ...                 ...
16636           0.0         0.0                   0.0                 0.0
16637          18.0         0.0                   6.0                84.0
16638           0.0         0.0                  18.0                 0.0
16639           0.0         0.0                  23.0                 0.0
16640           9.0         0.0                   7.0                 NaN

       constructor_wins  constructor_standings_pos  qualifying_time driver_age
0                   0.0                          0              0.0       34.0
1                   0.0                          0              0.2       28.0
2                   0.0                          0              0.3       33.0
3                   0.0                          0              0.6       30.0
4                   0.0                          0              0.7       28.0
...                 ...                        ...              ...        ...
16636               0.0                        NaN              3.0       26.0
16637               4.0                          1              0.9       31.0
16638               0.0                         10              1.3       35.0
16639               0.0                         11              0.6       35.0
16640               0.0                          6              2.8       34.0

[16641 rows x 22 columns]>

In [3]:
df.columns

Index(['Unnamed: 0', 'season', 'round', 'circuit_id', 'weather_warm',
       'weather_cold', 'weather_dry', 'weather_wet', 'weather_cloudy',
       'driver', 'nationality', 'constructor', 'grid', 'podium',
       'driver_points', 'driver_wins', 'driver_standings_pos',
       'constructor_points', 'constructor_wins', 'constructor_standings_pos',
       'qualifying_time', 'driver_age'],
      dtype='object')

In [ ]:
df = df.rename(columns={"season":"Sesion","round":"Recorrido","circuit_id":"Circuito", "weather_warm":"Clima Calido", "weather_cold":"Clima frio","weather_dry":"Clima seco", "weather_wet":"Clima lluvioso",
                          "weather_cloudy":"Clima nublado","driver": "Piloto", "nationality": "Nacionalidad","grid":"Grilla","podium":"Podio",  "constructor":"Constructores", })
df

,Unnamed: 0,Sesion,Recorrido,Circuito,Clima Calido,Clima frio,Clima seco,Clima lluvioso,Clima nublado,Piloto,...,Grilla,Podio,driver_points,driver_wins,driver_standings_pos,constructor_points,constructor_wins,constructor_standings_pos,qualifying_time,driver_age
0,14.0,1983.0,1.000000,Auto%#,False,0.0,True,0.0,False,keke_rosberg,...,1,15,0.0,0.0,0.0,0.0,0.0,0,0.0,34.0
1,5.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,False,prost,...,2,6,0.0,0.0,0.0,0.0,0.0,0,0.2,28.0
2,3.0,1983.0,9.199665,jacarepagua,False,0.0,True,0.0,False,tambay,...,3,4,0.0,0.0,0.0,0.0,0.0,0,0.3,33.0
3,0.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,NaN,piquet,...,4,1,0.0,0.0,0.0,0.0,0.0,0,0.6,30.0
4,6.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,False,warwick,...,5,7,0.0,0.0,0.0,0.0,0.0,0,0.7,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16636,4064.0,1993.0,1.000000,kyalami,True,0.0,False,0.0,False,blundell,...,8,NaN,0.0,0.0,0.0,0.0,0.0,NaN,3.0,26.0
16637,5893.0,1997.0,13.000000,monza,False,0.0,True,0.0,False,irvine,...,10,8,18.0,0.0,6.0,84.0,4.0,1,0.9,31.0
16638,9746.0,2008.0,7.000000,villeneuve,True,0.0,False,0.0,False,fisichella,...,17,14,0.0,0.0,18.0,0.0,0.0,10,1.3,35.0
16639,434.0,1984.0,3.000000,zolder,False,0.0,False,0.0,False,arnoux,...,2,3,0.0,0.0,23.0,0.0,0.0,11,0.6,35.0
16640,8554.0,2005.0,5.000000,catalunya,True,0.0,False,0.0,False,coulthard,...,9,8,9.0,0.0,7.0,NaN,0.0,6,2.8,34.0

In [ ]:
df["round"].unique()

array([ 1., nan,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21.])

In [21]:
df["round"].value_counts()

round
9.000000     958
10.000000    952
3.000000     949
11.000000    949
14.000000    944
8.000000     942
7.000000     940
12.000000    939
5.000000     937
1.000000     936
6.000000     925
4.000000     924
15.000000    921
2.000000     921
13.000000    912
16.000000    884
9.199665     499
17.000000    483
18.000000    307
19.000000    237
20.000000    113
21.000000     69
Name: count, dtype: int64

In [24]:
df["round"].isnull().sum()

np.int64(0)

In [28]:
df["round"]=df["round"].fillna(df["round"].mean())

In [29]:
df["round"]=df["round"].fillna("sin dato")

In [30]:
df

,Unnamed: 0,season,round,circuit_id,weather_warm,weather_cold,weather_dry,weather_wet,weather_cloudy,Piloto,...,grid,Podio,driver_points,driver_wins,driver_standings_pos,constructor_points,constructor_wins,constructor_standings_pos,qualifying_time,driver_age
0,14.0,1983.0,1.000000,Auto%#,False,0.0,True,0.0,False,keke_rosberg,...,1,15,0.0,0.0,0.0,0.0,0.0,0,0.0,34.0
1,5.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,False,prost,...,2,6,0.0,0.0,0.0,0.0,0.0,0,0.2,28.0
2,3.0,1983.0,9.199665,jacarepagua,False,0.0,True,0.0,False,tambay,...,3,4,0.0,0.0,0.0,0.0,0.0,0,0.3,33.0
3,0.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,NaN,piquet,...,4,1,0.0,0.0,0.0,0.0,0.0,0,0.6,30.0
4,6.0,1983.0,1.000000,jacarepagua,False,0.0,True,0.0,False,warwick,...,5,7,0.0,0.0,0.0,0.0,0.0,0,0.7,28.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16636,4064.0,1993.0,1.000000,kyalami,True,0.0,False,0.0,False,blundell,...,8,NaN,0.0,0.0,0.0,0.0,0.0,NaN,3.0,26.0
16637,5893.0,1997.0,13.000000,monza,False,0.0,True,0.0,False,irvine,...,10,8,18.0,0.0,6.0,84.0,4.0,1,0.9,31.0
16638,9746.0,2008.0,7.000000,villeneuve,True,0.0,False,0.0,False,fisichella,...,17,14,0.0,0.0,18.0,0.0,0.0,10,1.3,35.0
16639,434.0,1984.0,3.000000,zolder,False,0.0,False,0.0,False,arnoux,...,2,3,0.0,0.0,23.0,0.0,0.0,11,0.6,35.0
16640,8554.0,2005.0,5.000000,catalunya,True,0.0,False,0.0,False,coulthard,...,9,8,9.0,0.0,7.0,NaN,0.0,6,2.8,34.0

In [ ]:
df["cicuit_id"].unique()